/**
 * Index page — a list of all covered files with their percentages and
 * progress bars, linking to the per-file pages.
 */

import { escapeHtml } from './highlight';

export type FileSummary = {
    file: string;
    href: string;
    totalExec: number;
    coveredExec: number;
    /** Count of conditional-throw sites (throw_if / throw_unless) in this file. */
    throwsTotal: number;
    /** Count of those sites where the throw actually fired ≥1 time — i.e. the error branch was exercised. */
    throwsCovered: number;
    /**
     * Whether this file contributes to the overall totals. False for
     * vendored library code (stdlib.fc, etc.) that ships with FunC but
     * isn't owned by the user's project. Excluded files render BELOW a
     * separator row at the bottom of the table, and their lines/throws
     * are not summed into the header percentages.
     */
    counted: boolean;
};

function pctOf(covered: number, total: number): number {
    if (total === 0) return 100;
    return Math.round((covered / total) * 1000) / 10;
}

function renderRow(s: FileSummary, opts: { dimmed?: boolean } = {}): string {
    const linesPct = pctOf(s.coveredExec, s.totalExec);
    const throwsPct = pctOf(s.throwsCovered, s.throwsTotal);
    const throwsCell = s.throwsTotal === 0
        ? `<td class="num group-sep">—</td><td class="num">—</td><td class="pct">—</td><td class="bar"></td>`
        : `<td class="num group-sep">${s.throwsTotal}</td>` +
          `<td class="num">${s.throwsCovered}</td>` +
          `<td class="pct">${throwsPct}%</td>` +
          `<td class="bar"><div class="bar-track"><div class="bar-fill throws" style="width:${throwsPct}%"></div></div></td>`;
    const rowCls = opts.dimmed ? ' class="dimmed"' : '';
    return `<tr${rowCls}>
<td><a href="${escapeHtml(s.href)}">${escapeHtml(s.file)}</a></td>
<td class="num group-sep">${s.totalExec}</td>
<td class="num">${s.coveredExec}</td>
<td class="pct">${linesPct}%</td>
<td class="bar"><div class="bar-track"><div class="bar-fill" style="width:${linesPct}%"></div></div></td>
${throwsCell}
</tr>`;
}

export function renderIndexPage(summaries: readonly FileSummary[], version: string = ''): string {
    const counted = summaries.filter(s => s.counted).slice().sort((a, b) => a.file.localeCompare(b.file));
    const excluded = summaries.filter(s => !s.counted).slice().sort((a, b) => a.file.localeCompare(b.file));

    let grandLines = 0, grandLinesCov = 0, grandThrows = 0, grandThrowsCov = 0;
    for (const s of counted) {
        grandLines += s.totalExec;
        grandLinesCov += s.coveredExec;
        grandThrows += s.throwsTotal;
        grandThrowsCov += s.throwsCovered;
    }
    const grandLinesPct = pctOf(grandLinesCov, grandLines);
    const grandThrowsPct = pctOf(grandThrowsCov, grandThrows);

    const countedRows = counted.map(s => renderRow(s)).join('\n');
    const excludedRows = excluded.map(s => renderRow(s, { dimmed: true })).join('\n');
    const separatorRow = excluded.length > 0
        ? `<tr class="divider"><td colspan="9">Excluded from totals (vendored / stdlib)</td></tr>`
        : '';

    const throwsSummary = grandThrows === 0
        ? ''
        : ` · Throws: ${grandThrowsCov} / ${grandThrows} exercised (${grandThrowsPct}%)`;

    const footerLink = `<a href="https://github.com/Skydev0h/tonofcov" target="_blank" rel="noopener">tonofcov${version ? ` v${version}` : ''}</a>`;

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>tonofcov coverage report</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<header class="index-header">
<h1>tonofcov coverage report</h1>
<div class="summary">Lines: ${grandLinesCov} / ${grandLines} (${grandLinesPct}%)${throwsSummary}</div>
</header>
<table class="file-list">
<thead><tr>
<th rowspan="2">File</th>
<th colspan="4" class="pct group-sep">Lines</th>
<th colspan="4" class="pct group-sep">Conditional throws</th>
</tr><tr>
<th class="num group-sep">Total</th>
<th class="num">Hit</th>
<th class="pct">%</th>
<th class="bar"></th>
<th class="num group-sep">Total</th>
<th class="num">Fired</th>
<th class="pct">%</th>
<th class="bar"></th>
</tr></thead>
<tbody>
${countedRows}
${separatorRow}
${excludedRows}
</tbody>
</table>
<footer class="report-footer">generated by ${footerLink}</footer>
</body>
</html>
`;
}
